import { randomUUID } from "node:crypto";
import { DeviceIdentityManager, generateDeviceKeyPair, signPayload, type DeviceIdentity, type SignedPayload } from "../packages/provenance/src/DeviceIdentity";
import { composeSceneGraph, rendererAdapters } from "../packages/4d-engine/src/index";
import { sealManifest, verifyManifest } from "../packages/platform-seal/src/index";
import { runVerificationPipeline } from "../services/verification/src/pipeline";
import { appendForensicEvent, createForensicTrace } from "../packages/contracts/src/ForensicTrace";
import { validateObservationSeries } from "../packages/contracts/src/ObservationValidation";
import { activateWealthStrategies, BellChain, Bridge, CouncilOfGreatMinds, HyperfusionPlasmaLuminalStarSeed, QuantumBioAI, SandboxLedger, TeleOs } from "../sandbox/wealth-bridge/index";

const now = new Date();
const keys = generateDeviceKeyPair();
const device: DeviceIdentity = { deviceId: "device-demo-01", stationId: "station-demo-01", hardwareModel: "CH-EDGE-SIM", firmwareVersion: "1.0.0", sensorInventory: [{ sensorId: "temperature-dht22", type: "temperature", model: "DHT22", unit: "°C", samplingFrequency: 1, calibrationCertificate: "cert-demo", calibrationDate: "2026-08-01", calibrationExpiry: "2027-08-01", lastCalibrated: "2026-08-01", offset: 0, scale: 1 }], calibrationVersion: "cal-1", operationalStatus: "active", registeredAt: now.toISOString(), publicKey: keys.publicKey, keyId: "key-demo-1", keyVersion: 1 };
const identityManager = new DeviceIdentityManager();
identityManager.registerDevice(device);
const unsigned = { deviceId: device.deviceId, stationId: device.stationId, timestamp: now.toISOString(), nonce: randomUUID(), sequenceNumber: 1, payload: { temperatureC: 21.8 }, keyId: device.keyId, keyVersion: device.keyVersion };
const signed: SignedPayload = { ...unsigned, signature: signPayload(unsigned, keys.privateKey) };
const telemetryVerified = identityManager.verifySignedPayload(signed);
const stationValidation = validateObservationSeries([{ id: "obs-1", timestamp: "2026-08-19T17:00:00Z", latitude: -27.47, longitude: 153.02, value: 21.8, unit: "C" }, { id: "obs-2", timestamp: "2026-08-19T17:00:00Z", latitude: -27.47, longitude: 153.02, value: null, unit: "C" }, { id: "obs-3", timestamp: "bad-coordinate", latitude: 120, longitude: 153.02, value: 22.1, unit: "C" }]);
const verification = runVerificationPipeline({ forecast: [{ timestamp: "t0", value: 21 }, { timestamp: "t1", value: 22 }], observations: [{ timestamp: "t0", value: 20.5, quality: "excellent" }, { timestamp: "t1", value: 22.4, quality: "good" }], forecastAgeMinutes: 15, observationLatencyMinutes: 4, calibrationAgeDays: 10, provider: "sandbox-provider" });
let forensic = createForensicTrace({ traceId: "trace-demo-01", observationId: "obs-1", stationId: device.stationId, deviceId: device.deviceId, seriesId: "series-demo-01" });
forensic = appendForensicEvent(forensic, { stage: "observation", timestamp: now.toISOString(), status: "passed", referenceId: "obs-1", evidenceClass: "observed", details: { unit: "C" } });
forensic = appendForensicEvent(forensic, { stage: "device", timestamp: now.toISOString(), status: "passed", referenceId: device.deviceId, evidenceClass: "observed", details: { firmware: device.firmwareVersion } });
forensic = appendForensicEvent(forensic, { stage: "signature", timestamp: now.toISOString(), status: telemetryVerified ? "passed" : "failed", referenceId: device.keyId, evidenceClass: "observed", details: { algorithm: "Ed25519" } });
forensic = appendForensicEvent(forensic, { stage: "calibration", timestamp: now.toISOString(), status: "passed", referenceId: device.calibrationVersion, evidenceClass: "observed", details: { ageDays: 10 } });
forensic = appendForensicEvent(forensic, { stage: "ingestion", timestamp: now.toISOString(), status: "passed", referenceId: "ingest-demo-01", evidenceClass: "derived", details: { normalized: true } });
forensic = appendForensicEvent(forensic, { stage: "persistence", timestamp: now.toISOString(), status: "passed", referenceId: "db-demo-01", evidenceClass: "derived", details: {} });
forensic = appendForensicEvent(forensic, { stage: "forecast-comparison", timestamp: now.toISOString(), status: verification.mae !== null ? "passed" : "failed", referenceId: "verification-demo-01", evidenceClass: "derived", details: { mae: verification.mae } });
const scene = composeSceneGraph({ timestamp: now.toISOString(), layers: [{ id: "station", kind: "station", visible: true, opacity: 1, coordinateReferenceSystem: "WGS84", provenance: "device-demo-01", data: { stationId: device.stationId } }, { id: "forecast", kind: "forecast", visible: true, opacity: 0.8, coordinateReferenceSystem: "WGS84", provenance: "provider-demo", data: { values: [21, 22] } }] });
const renderedPlatforms = rendererAdapters.map((adapter) => adapter.render(scene));
const rotationKeys = generateDeviceKeyPair(); identityManager.rotateKey(device.deviceId, rotationKeys.publicKey, "key-demo-2"); identityManager.revokeKey(device.deviceId, "key-demo-2");
forensic = appendForensicEvent(forensic, { stage: "dashboard-rendering", timestamp: now.toISOString(), status: "passed", referenceId: "dashboard-vnext", evidenceClass: "derived", details: { layerCount: 2 } });
const driftCase = runVerificationPipeline({ forecast: [{ timestamp: "d0", value: 10 }], observations: [{ timestamp: "d0", value: 2, quality: "excellent" }], forecastAgeMinutes: 240, observationLatencyMinutes: 80, calibrationAgeDays: 220, provider: "sandbox-provider" });
const sealed = sealManifest({ application: "cosmic-hammer", version: "vnext-sim", commit: "local", buildId: "sim-001", schemaVersion: "db-v2", physicalTwinStateVersion: "v1", providerVersions: { openMeteo: "forecast" }, stationRegistryVersion: "demo", calibrationRegistryVersion: "cal-1", rendererVersion: "4d-scene-v1", configurationHash: "demo", databaseMigration: "0001", artifactHashes: {}, testResults: { passed: 0, failed: 0 }, securityVerification: telemetryVerified ? "ed25519-verified" : "failed", timestamp: now.toISOString() });
const seed = new HyperfusionPlasmaLuminalStarSeed(92.5, 0.99);
const bridge = new Bridge("Origin", "Destination", 3); bridge.addConnection("Alpha"); bridge.addConnection("Beta");
const bells = new BellChain(5); bells.ringBell(0); bells.ringBell(1);
const ledger = new SandboxLedger(); ledger.addBlock({ operation: "wealth-activation", financialExecution: false });
const council = new CouncilOfGreatMinds(["innovation", "ethics", "growth"]);
const teleOs = new TeleOs("CosmicSandbox"); teleOs.onboardVendor("vendor-demo", { name: "Sandbox Vendor" }); teleOs.bridgeAvenue("demo-channel");
const quantum = new QuantumBioAI("sandbox-model"); quantum.processStarSeedToNft({ name: "Luminal Core", attributes: ["rare", "energetic"] });
console.log(JSON.stringify({ trust: { deviceId: device.deviceId, telemetryVerified, provenance: identityManager.getProvenance(device.deviceId).map((record) => record.state) }, stationValidation, verification, driftCase, forensic, scene: { version: scene.version, layerCount: scene.layers.length, renderedPlatforms }, seal: { valid: verifyManifest(sealed), hash: sealed.sealHash }, wealthBridge: { strategies: activateWealthStrategies(), fusion: seed.generateFusionReaction(), starSeed: seed.seedStarFormation(), bridge: bridge.getPathDetails(), bells: bells.getChainState(), ledgerValid: ledger.verify(), councilApproved: council.evaluateOpportunity({ innovative: true, ethical: true, growth: true }), teleOs: teleOs.getNetworkStatus(), doorway: quantum.findDoorwayState({ demand: 0.9, liquidity: 0.85 }) } }, null, 2));
